name: Actionlint

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/workflows/actionlint.yml'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.0
