name: ShellCheck

on:
  push:
    paths:
      - 'fedora-setup.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'fedora-setup.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
          check_together: true
          path: fedora-setup.sh
